Teachers/urls.py
from django.urls import path

from Teachers.views import ListTeacherView
from Teachers.views import CreateTeacherView
from Teachers.views import UpdateTeacherView
from Teachers.views import DetailTeacherView
from Teachers.views import DeleteTeacherView

app_name = 'teachers'

urlpatterns = [
    path('', ListTeacherView.as_view(), name='list'),
    path('create/', CreateTeacherView.as_view(), name='create'),
    path('update/<int:pk>/', UpdateTeacherView.as_view(), name='update'),
    path('detail/<int:pk>/', DetailTeacherView.as_view(), name='detail'),
    path('delete/<int:pk>/', DeleteTeacherView.as_view(), name='delete'),
]

lms/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),

    path('students/', include('students.urls')),

    path('teachers/', include('Teachers.urls')),

    path('groups/', include('groups.urls')),

    path('courses/', include('courses.urls')),

    path('accounts/', include('accounts.urls')),

    path('accounts/', include('django.contrib.auth.urls')),

    path('__debug__/', include('debug_toolbar.urls')),

]

Teachers/models.py
from random import randint

from django.db import models

from core.models import PersonModel


class Teacher(PersonModel):                    #
    salary = models.PositiveIntegerField(default=10_000)

    class Meta:
        db_table = 'teachers'

    def __str__(self):
        return f'{self.first_name} {self.last_name} (${self.salary})'

    @classmethod
    def _generate(cls):
        teacher = super()._generate()
        teacher.salary = randint(10_000, 100_000)
        teacher.save()

Teachers/forms.py
from django import forms
from django_filters import FilterSet

from Teachers.models import Teacher


class CreateTeacherForm(forms.ModelForm):
    class Meta:
        model = Teacher
        fields = [
            'first_name',
            'last_name',
            'birthday',
            'salary',
        ]
        widgets = {
            'birthday': forms.DateInput(attrs={"type": 'date'})
        }


class UpdateTeacherForm(forms.ModelForm):              #
    class Meta:
        model = Teacher
        fields = [
            'first_name',
            'last_name',
            'birthday',
            'salary',
        ]
        widgets = {
            'birthday': forms.DateInput(attrs={"type": 'date'})
        }


class TeacherFilterForm(FilterSet):

    class Meta:
        model = Teacher
        fields = {
            'first_name': ['exact', 'icontains'],
            'last_name': ['exact', 'startswith']
        }

Teachers/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db.models import Q
from django.http import HttpResponse, HttpResponseRedirect
from django.middleware.csrf import get_token
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from webargs.djangoparser import use_args
from Teachers.forms import CreateTeacherForm, UpdateTeacherForm, TeacherFilterForm
from webargs.fields import Str
from .models import Teacher
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView


class ListTeacherView(ListView):
    model = Teacher
    template_name = 'teachers/list.html'


class DetailTeacherView(LoginRequiredMixin, DetailView):
    model = Teacher
    template_name = 'teachers/detail.html'


class CreateTeacherView(LoginRequiredMixin, CreateView):
    model = Teacher
    form_class = CreateTeacherForm
    success_url = reverse_lazy('teachers:list')
    template_name = 'teachers/create.html'


class UpdateTeacherView(LoginRequiredMixin, UpdateView):
    model = Teacher
    form_class = UpdateTeacherForm
    success_url = reverse_lazy('teachers:list')
    template_name = 'teachers/update.html'


class DeleteTeacherView(LoginRequiredMixin, DeleteView):
    model = Teacher
    success_url = reverse_lazy('teachers:list')
    template_name = 'teachers/delete.html'

Teachers/templates/teachers/create.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}
Create new teacher
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="text-center">
                    <input class="btn btn-outline-primary" type="submit" value="Create">
                    <a class="btn btn-outline-primary" href="{% url 'teachers:list' %}">Back to list</a>
                </div>
            </form>
        </div>
        <div class="col-3"></div>
    </div>
{% endblock %}

Teachers/templates/teachers/delete.html
{% extends 'base.html' %}

{% block title %}
Delete student "{{ teacher.first_name }}"
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col">
            <form method="post">
                {% csrf_token %}
                <div class="text-center">
                    <p>Do you really want to remove student <strong>"{{ teacher.first_name }} {{ teacher.last_name }}"</strong></p>
                    <input class="btn btn-outline-primary" type="submit" value="Agree">
                    <a class="btn btn-outline-primary" href="{% url 'teachers:list' %}">Back to list</a>
                </div>
            </form>
        </div>
        <div class="col-3"></div>
    </div>
{% endblock %}

Teachers/templates/teachers/detail.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col align-self-center">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">{{ teacher.last_name }} {{ teacher.first_name }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{ teacher.salary }}</h6>
                <p class="card-text">{{ teacher.birthdate|date:"y M Y" }}</p>
                <div class="text-center">
                    <a class="btn btn-outline-primary" href="{% url 'teachers:update' teacher.pk %}">Edit</a>
                    <a class="btn btn-outline-primary" href="{% url 'teachers:list' %}">Back to list</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

Teachers/templates/teachers/list.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}List of teachers{% endblock %}

{% block content %}
    <div class="row">
        <div class="accordion" id="accordionExample">
            <div class="accordion-item">
                <h2 class="accordion-header" id="headingOne">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        Search
                    </button>
                </h2>
                <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne"
                     data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                        <div class="col-3"></div>
                        <div class="col">
                            <form method="get">
                                {{ filter_form.form|crispy }}
                                <input class="btn btn-outline-primary mt-3" type="submit" value="Search">
                            </form>
                        </div>
                        <div class="col-3"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
    <table class="table table-striped table-hover">
        <thead>
            <tr class="text-center">
                <th>First name</th>
                <th>Last name</th>
                <th>Birthday</th>
                {% if user.is_authenticated %}
                    <th><i class="bi bi-pencil-fill"></i></th>
                    <th><i class="bi bi-trash3-fill"></i></th>
                {% endif %}
            </tr>
        <thead>
        <tbody>
            {% for st in object_list %}
                <tr>
                    <td>{{ forloop.counter}}</td>
                    {% if user.is_authenticated %}
                        <td><a href="{% url 'teachers:detail' st.pk %}">{{ st.first_name }}</a></td>
                    {% else %}
                        <td>{{ st.first_name }}</td>
                    {% endif %}
                    <td>{{st.last_name}}</td>
                    <td class="text-center">{{ st.birthdate|date:"d M Y" }}</td>
                    {% if user.is_authenticated %}
                        <td class="text-center"><a class="btn btn-outline-primary btn-sm" href="{% url 'teachers:update' st.pk %}">Edit</a></td>
                        <td class="text-center"><a class="btn btn-outline-danger btn-sm" href="{% url 'teachers:delete' st.pk %}">Remove</a></td>
                    {% endif %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>
{% endblock %}

Teachers/templates/teachers/update.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}
Update teacher "{{ form.first_name.value }}"
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="text-center">
                    <input class="btn btn-outline-primary" type="submit" value="Udate">
                    <a class="btn btn-outline-primary" href="{% url 'teachers:list' %}">Back to list</a>
                </div>
            </form>
        </div>
        <div class="col-3"></div>
    </div>
{% endblock %}