accounts/urls.py
from django.urls import path

from .views import AccountRegisterView, profile_view, UpdateProfileView
from .views import AccountLoginView
from .views import AccountLogoutView

app_name = 'accounts'

urlpatterns = [
    path('register/', AccountRegisterView.as_view(), name='register'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', profile_view, name='profile'),
    path('profile/update/', UpdateProfileView.as_view(), name='profile_update'),
]

lms/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),

    path('students/', include('students.urls')),

    path('teachers/', include('Teachers.urls')),

    path('groups/', include('groups.urls')),

    path('courses/', include('courses.urls')),

    path('accounts/', include('accounts.urls')),

    path('accounts/', include('django.contrib.auth.urls')),

    path('__debug__/', include('debug_toolbar.urls')),

]

accounts/models.py
from django.contrib.auth.models import User
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save


class Profile(models.Model):
    used = models.OneToOneField(User, on_delete=models.CASCADE)
    birthday = models.DateField(null=True, blank=True)
    city = models.CharField(null=True, blank=True, max_length=50)

    class Meta:
        db_table = 'profiles'


@receiver(post_save, sender=User)
def create_profile(sender, **kwargs):
    if kwargs.get('created'):
        profile = Profile(user=kwargs.get('instance'))
        profile.save()

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from django import forms
from accounts.models import Profile


class UserRegisterForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        fields = [
            'username',
            'email',
            'first_name',
            'last_name',

        ]


class UserUpdateForm(UserChangeForm):
    password = None

    class Meta(UserChangeForm.Meta):
        fields = ['first_name', 'last_name', 'email']


class ProfileUpdateForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['birthday', 'city']

        widgets = {'birthday': forms.DateInput(attrs={'type': 'date'})}

accounts/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import LoginView, LogoutView
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView
from django.views.generic.edit import ProcessFormView
from django.contrib import messages

from accounts.forms import UserRegisterForm, UserUpdateForm, ProfileUpdateForm


class AccountRegisterView(CreateView):
    model = User
    form_class = UserRegisterForm
    success_url = reverse_lazy('home')
    template_name = 'accounts/register.html'


class AccountLoginView(LoginView):
    template_name = 'accounts/login.html'

    def form_valid(self, form):
        response = super().form_valid(form)
        messages.success(self.request, f'user <{self.request.user}> logged in.')

        return response


class AccountLogoutView(LogoutView):
    template_name = 'accounts/logout.html'


@login_required
def profile_view(request):
    return render(request, 'accounts/profile.html')


class UpdateProfileView(LoginRequiredMixin, ProcessFormView):
    def get(self, request, *args, **kwargs):
        user = request.user
        profile = user.profile
        user_form = UserUpdateForm(instance=user)
        profile_form = ProfileUpdateForm(instance=profile)

        return render(request, 'accounts/update.html', {'user_form': user_form, 'profile_form': profile_form})

    def post(self, request, *args, **kwargs):
        user = request.user
        profile = user.profile
        user_form = UserUpdateForm(instance=user, data=request.POST)
        profile_form = ProfileUpdateForm(instance=profile, data=request.POST)

        if user_form.is_valid() and profile_form.is_valid():
            user_form.save()
            profile_form.save()

            return HttpResponseRedirect(reverse('accounts:profile'))

accounts/templates/accounts/login.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}
Sign In
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <a href="{% url 'password_reset' %}">If you Firgot your password, click here.</a>
                <div class="text-center pt-3">
                    <input class="btn btn-outline-primary" type="submit" value="SignIn">
                    <a class="btn btn-outline-primary" href="{% url 'accounts:register' %}">SignUp</a>
                </div>
            </form>
        </div>
        <div class="col-3"></div>
    </div>
{% endblock %}

accounts/templates/accounts/logout.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}
Sign In
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col">
            <div class="text-center">
                <a href="{% url 'home' %}" class="btn btn-outline-primary">Home</a>
                <a href="{% url 'accounts:login' %}" class="btn btn-outline-primary">SignIn</a>
                <a href="{% url 'accounts:register' %}" class="btn btn-outline-primary">SignUp</a>
            </div>
        </div>
        <div class="col-3"></div>
    </div>
{% endblock %}

accounts/templates/accounts/profile.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}
User profile
{% endblock %}

{% block content %}
        <div class="row">
            <div class="col-3"></div>
            <div class="col">
                <div class="p-3 m-3">
                    <h2 class="account-heading">{{ user.last_name }} {{ user.first_name }}</h2>
                    <p class="text-secondary">{{ user.email }}</p>
                </div>
                <ul class="list-group list-group-flash">
                    <li class="list-group-item"><span class="h5">Username: </span>{{ user.username }}</li>
                    <li class="list-group-item">
                        <span class="h5">Birthday: </span>
                        {% if user.profile.birthday %}{{ user.profile.birthday }}{% endif %}
                    </li>
                    <li class="list-group-item">
                        <span class="h5">City: </span>
                        {% if user.profile.city %}{{ user.profile.city }}{% endif %}
                    </li>
                </ul>
                <div class="text-center mt-5">
                    <a class="btn btn-outline-primary" href="{% url 'home' %}">Back to home</a>
                    <a class="btn btn-outline-primary" href="{% url 'accounts:profile_update' %}">Edit profile</a>
                </div>
            </div>
            <div class="col-3"></div>
        </div>
{% endblock %}

accounts/templates/accounts/register.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}
Sign Up
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="text-center">
                    <input class="btn btn-outline-primary" type="submit" value="SignUp">
                    <a class="btn btn-outline-primary" href="{% url 'accounts:login' %}">SignIn</a>
                </div>
            </form>
        </div>
        <div class="col-3"></div>
    </div>
{% endblock %}

accounts/templates/accounts/update.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}
Update profile
{% endblock %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        <div class="row">
            <div class="col-3"></div>
            <div class="col">
                {{ user_form|crispy }}
                {{ profile_form|crispy }}
                <div class="text-center mt-5">
                    <a class="btn btn-outline-primary" href="{% url 'accounts:profile' %}">Back</a>
                    <input class="btn btn-outline-primary" type="submit" value="Update">
                </div>
            </div>
            <div class="col-3"></div>
        </div>
    </form>
{% endblock %}