Teachers/urls.py
from django.urls import path

from Teachers.views import ListTeacherView
from Teachers.views import CreateTeacherView
from Teachers.views import UpdateTeacherView
from Teachers.views import DetailTeacherView
from Teachers.views import DeleteTeacherView

app_name = 'teachers'

urlpatterns = [
    path('', ListTeacherView.as_view(), name='list'),
    path('create/', CreateTeacherView.as_view(), name='create'),
    path('update/<int:pk>/', UpdateTeacherView.as_view(), name='update'),
    path('detail/<int:pk>/', DetailTeacherView.as_view(), name='detail'),
    path('delete/<int:pk>/', DeleteTeacherView.as_view(), name='delete'),
]

accounts/urls.py
from django.urls import path

from .views import AccountRegisterView, profile_view, UpdateProfileView
from .views import AccountLoginView
from .views import AccountLogoutView

app_name = 'accounts'

urlpatterns = [
    path('register/', AccountRegisterView.as_view(), name='register'),
    path('login/', AccountLoginView.as_view(), name='login'),
    path('logout/', AccountLogoutView.as_view(), name='logout'),
    path('profile/', profile_view, name='profile'),
    path('profile/update/', UpdateProfileView.as_view(), name='profile_update'),
]

courses/urls.py
from django.urls import path

from courses.views import get_courses
from courses.views import create_course_view
from courses.views import UpdateCourseView
from courses.views import detail_course
from courses.views import delete_course

app_name = 'courses'

urlpatterns = [
    path('', get_courses, name='list'),
    path('create/', create_course_view, name='create'),
    path('update/<int:pk>/', UpdateCourseView.as_view(), name='update'),
    path('detail/<int:pk>/', detail_course, name='detail'),
    path('delete/<int:pk>/', delete_course, name='delete'),
]

groups/urls.py
from django.urls import path


from .views import CreateGroupView
from .views import DetailGroupView
from .views import DeleteGroupView
from .views import ListGroupView
from .views import UpdateGroupView

app_name = 'groups'

urlpatterns = [
    path('', ListGroupView.as_view(), name='list'),
    path('create/', CreateGroupView.as_view(), name='create'),
    path('update/<int:pk>/', UpdateGroupView.as_view(), name='update'),
    path('detail/<int:pk>/', DetailGroupView.as_view(), name='detail'),
    path('delete/<int:pk>/', DeleteGroupView.as_view(), name='delete'),
]

lms/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),

    path('students/', include('students.urls')),

    path('teachers/', include('Teachers.urls')),

    path('groups/', include('groups.urls')),

    path('courses/', include('courses.urls')),

    path('accounts/', include('accounts.urls')),

    path('accounts/', include('django.contrib.auth.urls')),

    path('__debug__/', include('debug_toolbar.urls')),

]

students/urls.py
from django.urls import path

from students.views import create_student_view
from students.views import UpdateStudentView
from students.views import detail_student
from students.views import delete_student
from .views import ListStudentView

app_name = 'students'

urlpatterns = [
    path('', ListStudentView.as_view(), name='list'),
    path('create/', create_student_view, name='create'),
    path('update/<int:pk>/', UpdateStudentView.as_view(), name='update'),
    path('detail/<int:pk>/', detail_student, name='detail'),
    path('delete/<int:pk>/', delete_student, name='delete'),
]

groups/models.py
from django.db import models
import datetime
from Teachers.models import Teacher
from core.models import BaseModel

from groups.validators import validate_start_date


class Group(BaseModel):
    group_name = models.CharField(max_length=50, verbose_name='group name', db_column='g_name')
    group_start = models.DateField(default=datetime.date.today)
    group_text = models.TextField(null=True, blank=True)
    headman = models.OneToOneField(
        'students.Student', on_delete=models.SET_NULL, null=True, blank=True, related_name='headman_group'
    )
    teachers = models.ManyToManyField(to=Teacher, blank=True, related_name='groups')

    class Meta:
        db_table = 'groups'

    def __str__(self):
        return f'Grope name: {self.group_name}'

    @classmethod
    def generate_fake_data(cls):
        for name in 'Python', 'Java', 'C++', 'PM', 'QA', 'C#':
            cls.objects.create(group_name=name)

students/models.py
import datetime
from random import choice

from dateutil.relativedelta import relativedelta
from django.db import models
from faker import Faker

from core.models import PersonModel
from groups.models import Group
from students.validators import ValidateEmailDomain, validate_unique_email

VALID_DOMAINS = ('gmail.com', 'yahoo.com', 'test.com')


class Student(PersonModel):

    group = models.ForeignKey(Group, on_delete=models.SET_NULL, null=True, related_name='students')

    class Meta:
        db_table = 'students'

    def __str__(self):
        if self.group:
            return f'{self.first_name} {self.last_name} ({self.group.group_name})'
        else:
            return f'{self.first_name} {self.last_name} ()'

    def get_age(self):
        return relativedelta(datetime.date.today(), self.birthday).years

    @classmethod
    def _generate(cls):
        groups = Group.objects.all()
        student = super()._generate()
        student.group = choice(groups)
        student.save()

groups/forms.py
from django import forms
from django_filters import FilterSet

from groups.models import Group
from students.models import Student


class GroupBaseForm(forms.ModelForm):
    students = forms.ModelMultipleChoiceField(queryset=None, required=False)

    # def save(self, commit=True):
    #     new_group = super().save(commit)
    #     students = self.cleaned_data['students']
    #     for student in students:
    #         student.group = new_group
    #         student.save()

    class Meta:
        model = Group
        fields = '__all__'

        widgets = {
            'group_start': forms.DateInput(attrs={"type": 'date'})
        }


class CreateGroupForm(GroupBaseForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['students'].queryset = Student.objects.filter(group__isnull=True).select_related('group')

    class Meta(GroupBaseForm.Meta):
        exclude = [
            'headman',
        ]


class UpdateGroupForm(GroupBaseForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['students'].queryset = Student.objects.all().select_related('group')
        self.fields['headman_field'] = forms.ChoiceField(
            choices=[(st.pk, f'{st.first_name} {st.last_name}') for st in self.instance.students.all()],
            label='Headman',
            required=False
        )
        self.fields['headman_field'].choices.insert(0, (0, '----------'))

    class Meta(GroupBaseForm.Meta):
        exclude = [
            'start_date',
            'headman'
        ]


class GroupFilterForm(FilterSet):

    class Meta:
        model = Group
        fields = {
            'group_name': ['exact', 'icontains', 'startswith']
        }

students/forms.py
from django import forms
from django_filters import FilterSet

from students.models import Student


class CreateStudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = [
            'first_name',
            'last_name',
            'birthday',
            'email',
            'city',
            'phone',
        ]

        widgets = {
            'birthday': forms.DateInput(attrs={"type": 'date'})
        }

    def clean_phone(self):
        value = self.cleaned_data.get('phone')

        return ''.join(filter(lambda x: x in ['0','1','2','3','4','5','6','7','8','9','(',')','-','+'], value))

    def clean_first_name(self):
        value = self.cleaned_data.get('first_name')

        return value.capitalize()


class UpdateStudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = [
            'first_name',
            'last_name',
            'birthday',
            'city',
        ]

        widgets = {
            'birthday': forms.DateInput(attrs={"type": 'date'})
        }


class StudentFilterForm(FilterSet):

    class Meta:
        model = Student
        fields = {
            'first_name': ['exact', 'icontains'],
            'last_name': ['exact', 'startswith']
        }

groups/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from django.urls import reverse, reverse_lazy

from groups.forms import CreateGroupForm, UpdateGroupForm
from groups.models import Group

from students.models import Student


class ListGroupView(ListView):
    model = Group
    template_name = 'groups/list.html'


class DetailGroupView(LoginRequiredMixin, DetailView):
    model = Group
    template_name = 'groups/detail.html'


class CreateGroupView(LoginRequiredMixin, CreateView):
    model = Group
    form_class = CreateGroupForm
    success_url = reverse_lazy('groups:list')
    template_name = 'groups/create.html'

    def form_valid(self, form):
        response = super().form_valid(form)
        new_group = form.save()
        students = form.cleaned_data['students']
        for student in students:
            student.group = new_group
            student.save()
        return response


class UpdateGroupView(LoginRequiredMixin, UpdateView):
    model = Group
    form_class = UpdateGroupForm
    success_url = reverse_lazy('groups:list')
    template_name = 'groups/update.html'

    def get_initial(self):
        initial = super().get_initial()
        try:
            initial['headman_field'] = self.object.headman.pk
        except AttributeError:
            pass

        return initial

    def form_valid(self, form):
        response = super().form_valid(form)
        students = form.cleaned_data['students']
        for student in students:
            student.group = self.object
            student.save()

        headman_pk = int(form.cleaned_data.get('headman_field'))
        if headman_pk:
            form.instance.headman = Student.objects.get(pk=headman_pk)
        else:
            form.instance.headman = None
        form.save()

        return response


class DeleteGroupView(LoginRequiredMixin, DeleteView):
    model = Group
    success_url = reverse_lazy('groups:list')
    template_name = 'groups/delete.html'

students/views.py
from copy import copy
from django.core.paginator import Paginator, Page

from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.urls import reverse, reverse_lazy
from .forms import CreateStudentForm, UpdateStudentForm, StudentFilterForm
from .models import Student
from django.views.generic import ListView, CreateView, UpdateView


class ListStudentView(ListView):
    model = Student
    template_name = 'students/list.html'
    paginate_by = 5

    def get_filter(self):
        students = Student.objects.all().order_by('birthday').select_related('group', 'headman_group')
        filter_form = StudentFilterForm(data=self.request.GET, queryset=students)
        return filter_form

    def get_queryset(self):
        return self.get_filter().qs

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = self.get_filter().form

        params = self.request.GET
        if 'page' in params:
            params = copy(params)
            del params['page']

        context['params'] = f'&{params.urlencode()}' if params else ''

        return context


@login_required
def detail_student(request, pk):
    student = get_object_or_404(Student, pk=pk)
    return render(request, 'students/detail.html', {'title': 'Detail of student','student': student})


@login_required
def create_student_view(request):
    if request.method == 'GET':
        form = CreateStudentForm()
    elif request.method == 'POST':
        form = CreateStudentForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('students:list'))

    return render(request, 'students/create.html', {'form': form})


class UpdateStudentView(LoginRequiredMixin, UpdateView):
    model = Student
    form_class = UpdateStudentForm
    success_url = reverse_lazy('students:list')
    template_name = 'students/update.html'


@login_required
def delete_student(request, pk):
    st = get_object_or_404(Student, pk=pk)
    if request.method == 'POST':
        st.delete()
        return HttpResponseRedirect(reverse('students:list'))
    return render(request, 'students/delete.html', {'student': st})

templates/includes/groups_table.html
  <table class="table table-striped table-hover">
        <thead>
            <tr class="text-center">
                <th>First name</th>
                <th>Last name</th>
                {% if not is_course %}
                    <th><i class="bi bi-pencil-fill"></i></th>
                    <th><i class="bi bi-trash3-fill"></i></th>
                {% endif %}
            </tr>
        <thead>
        <tbody>
            {% for st in object_list %}
                <tr>
                    <td>{{ forloop.counter}}</td>
                    <td><a href="{% url 'groups:detail' st.pk %}">{{ st.group_name }}</a></td>
                    <td>{{ st.last_name }}</td>
                    <td class="text-center">{{ st.group_start|date:"d M Y" }}</td>
                    {% if not is_group %}
                        <td class="text-center"><a class="btn btn-outline-primary btn-sm" href="{% url 'groups:update' st.pk %}">Edit</a></td>
                        <td class="text-center"><a class="btn btn-outline-danger btn-sm" href="{% url 'groups:delete' st.pk %}">Remove</a></td>
                    {% endif %}
                </tr>
            {% endfor %}
        </tbody>
    </table>

templates/includes/messages.html
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{% if message.tags == 'error' %}danger{% else %}{{ message.tags }}{% endif %}" role="alert">
            {{ message }}
        </div>
    {% endfor %}
{% endif %}

templates/includes/navbar.html
<nav class="navbar navbar-expand-lg fixed-top" style="background-color: #e3f2fd;">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">LMS</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Students
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'students:list' %}">List</a></li>
                        {% if user.is_authenticated %}
                            <li><a class="dropdown-item" href="{% url 'students:create' %}">Create</a></li>
                        {% endif %}
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Groups
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'groups:list' %}">List</a></li>
                        {% if user.is_authenticated %}
                            <li><a class="dropdown-item" href="{% url 'groups:create' %}">Create</a></li>
                        {% endif %}
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Course
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'courses:list' %}">List</a></li>
                        {% if user.is_authenticated %}
                            <li><a class="dropdown-item" href="{% url 'courses:create' %}">Create</a></li>
                        {% endif %}
                    </ul>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                        Teachers
                    </a>
                    <ul class="dropdown-menu">
                        <li><a class="dropdown-item" href="{% url 'teachers:list' %}">List</a></li>
                        {% if user.is_authenticated %}
                            <li><a class="dropdown-item" href="{% url 'teachers:create' %}">Create</a></li>
                        {% endif %}
                    </ul>
                </li>
            </ul>
            <div class="d-flex">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            {% if user.is_authenticated %}
                                {{ user.username }}
                            {% else %}
                                No name
                            {% endif %}
                        </a>
                        <ul class="dropdown-menu">
                            {% if user.is_authenticated %}
                                <li><a class="dropdown-item" href="{% url 'accounts:profile' %}">Profile</a></li>
                                <li><a class="dropdown-item" href="{% url 'password_change' %}">Password change</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="{% url 'accounts:logout' %}">SignOut</a></li>
                            {% else %}
                                <li><a class="dropdown-item" href="{% url 'accounts:register' %}">SignUp</a></li>
                                <li><a class="dropdown-item" href="{% url 'accounts:login' %}">SignIn</a></li>
                                <li><hr class="dropdown-divider"></li>
                                <li><a class="dropdown-item" href="{% url 'password_reset' %}">Password change</a></li>
                            {% endif %}
                        </ul>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</nav>

templates/includes/paginator.html
<nav aria-label="Page navigation example">
    <ul class="pagination justify-content-center">
        {% if page_obj.has_previous %}
            <li class="page-item"><a class="page-link" href="?page=1{{ params }}"><i class="bi bi-chevron-double-left"></i></a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}{{ params }}"><i
                    class="bi bi-chevron-left"></i></a></li>
        {% else %}
            <li class="page-item disabled"><a class="page-link"><i class="bi bi-chevron-double-left"></i></a></li>
            <li class="page-item disabled"><a class="page-link"><i class="bi bi-chevron-left"></i></a></li>
        {% endif %}

        {% for num in page_obj.paginator.page_range %}
            {% if num == page_obj.number %}
                <li class="page-item"><a class="page-link active">{{ num }}</a></li>
            {% elif num > page_obj.number|add:-3 and num < page_obj.number|add:3 %}
            <!--     num > page_obj.number + (-3) and num < page_obj.number + 3  -->
            <!--                          page_obj.number = 5                    -->
            <!--                                num ==> 3, 4, 6, 7               -->
                <li class="page-item"><a class="page-link" href="?page={{ num }}{{ params }}">{{ num }}</a></li>
            {% endif %}

        {% endfor %}

        {% if page_obj.has_next %}
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}{{ params }}"><i
                    class="bi bi-chevron-right"></i></a></li>
            <li class="page-item"><a class="page-link" href="?page={{ page_obj.paginator.num_pages }}{{ params }}"><i
                    class="bi bi-chevron-double-right"></i></a></li>
        {% else %}
            <li class="page-item disabled"><a class="page-link"><i class="bi bi-chevron-right"></i></a></li>
            <li class="page-item disabled"><a class="page-link"><i class="bi bi-chevron-double-right"></i></a></li>
        {% endif %}
    </ul>
</nav>

templates/includes/students_table.html
    <table class="table table-striped table-hover">
        <thead>
            <tr class="text-center">
                <th>First name</th>
                <th>Last name</th>
                <th>Birthday</th>
                <th>Age</th>
                <th>Headman</th>
                {% if not is_group %}
                    <th>Group</th>
                    {% if user.is_authenticated %}
                        <th><i class="bi bi-pencil-fill"></i></th>
                        <th><i class="bi bi-trash3-fill"></i></th>
                    {% endif %}
                {% endif %}
            </tr>
        <thead>
        <tbody>
            {% for st in page_obj %}
                <tr>
                    <td>{{ forloop.counter0|add:page_obj.start_index }}</td>
                    {% if user.is_authenticated %}
                        <td><a href="{% url 'students:detail' st.pk %}">{{ st.first_name }}</a></td>
                    {% else %}
                        <td>{{ st.first_name }}</td>
                    {% endif %}
                    <td>{{ st.last_name }}</td>
                    <td class="text-center">{{ st.birthday|date:"d M Y" }}</td>
                    <td class="text-center">{{ st.get_age }}</td>
                    <td class="text-center">
                        {% if st.headman_group %}
                            <i class="bi bi-check2-circle"></i></td>
                        {% endif %}
                    {% if not is_group %}
                        <td>{{ st.group.name }}</td>
                        {% if user.is_authenticated %}
                        <td class="text-center"><a class="btn btn-outline-primary btn-sm"
                                                   href="{% url 'students:update' st.pk %}">Edit</a></td>
                        <td class="text-center"><a class="btn btn-outline-danger btn-sm"
                                                   href="{% url 'students:delete' st.pk %}">Remove</a></td>
                        {% endif %}
                    {% endif %}
                </tr>
            {% endfor %}
        </tbody>
    </table>