courses/urls.py
from django.urls import path

from courses.views import get_courses
from courses.views import create_course_view
from courses.views import UpdateCourseView
from courses.views import detail_course
from courses.views import delete_course

app_name = 'courses'

urlpatterns = [
    path('', get_courses, name='list'),
    path('create/', create_course_view, name='create'),
    path('update/<int:pk>/', UpdateCourseView.as_view(), name='update'),
    path('detail/<int:pk>/', detail_course, name='detail'),
    path('delete/<int:pk>/', delete_course, name='delete'),
]

lms/urls.py
from django.contrib import admin
from django.urls import path, include

from core.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='home'),

    path('students/', include('students.urls')),

    path('teachers/', include('Teachers.urls')),

    path('groups/', include('groups.urls')),

    path('courses/', include('courses.urls')),

    path('accounts/', include('accounts.urls')),

    path('accounts/', include('django.contrib.auth.urls')),

    path('__debug__/', include('debug_toolbar.urls')),

]

courses/models.py
from django.db import models
import datetime
from core.models import BaseModel
from groups.models import Group


class Course(BaseModel):
    name = models.CharField(
        max_length=50,
        verbose_name='course name',
        db_column='c_name'
    )
    course_start = models.DateField(default=datetime.date.today)
    course_text = models.TextField(null=True, blank=True)
    course_group = models.OneToOneField(
        Group,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name='course_group'
    )

    class Meta:
        db_table = 'courses'

    def __str__(self):
        return f'Grope name: {self.name}'

    @classmethod
    def generate_fake_data(cls):
        for name in 'Course_1', 'Course_2', 'Course_3', 'Course_4', 'Course_5':
            cls.objects.create(name=name)

courses/forms.py
from django import forms
from django_filters import FilterSet

from courses.models import Course

"""
Не уверен может быть create и update нужно было в один класс и наследоватьс,
или же заменить их одним 
оставлю так пока
"""


class CreateCourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = '__all__'

        widgets = {
            'course_start': forms.DateInput(attrs={"type": 'date'})
        }


class UpdateCourseForm(forms.ModelForm):
    class Meta:
        model = Course
        fields = '__all__'

        widgets = {
            'course_start': forms.DateInput(attrs={"type": 'date'})
        }


class CourseFilterForm(FilterSet):

    class Meta:
        model = Course
        fields = {
            'name': ['exact', 'icontains', 'startswith']
        }

courses/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from django.views.generic import UpdateView

from courses.forms import CreateCourseForm, UpdateCourseForm
from courses.models import Course
from django.urls import reverse, reverse_lazy


def get_courses(request):
    courses = Course.objects.all()
    return render(request, 'courses/list.html', {'courses': courses})


@login_required
def detail_course(request, pk):
    course = get_object_or_404(Course, pk=pk)
    return render(request, 'course/detail.html', {'title': 'Detail of group', 'course': course})


@login_required
def create_course_view(request):
    if request.method == 'GET':
        form = CreateCourseForm()
    elif request.method == 'POST':
        form = CreateCourseForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('courses:list'))

    return render(request, 'courses/create.html', {'form': form})


class UpdateCourseView(LoginRequiredMixin, UpdateView):
    model = Course
    form_class = UpdateCourseForm
    success_url = reverse_lazy('courses:list')
    template_name = 'courses/update.html'


@login_required
def delete_course(request, pk):
    st = get_object_or_404(Course, pk=pk)
    if request.method == 'POST':
        st.delete()
        return HttpResponseRedirect(reverse('courses:list'))
    return render(request, 'courses/delete.html', {'course': st})

courses/templates/courses/create.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}
Create new Course
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="text-center">
                    <input class="btn btn-outline-primary" type="submit" value="Create">
                    <a class="btn btn-outline-primary" href="{% url 'courses:list' %}">Back to list</a>
                </div>
            </form>
        </div>
        <div class="col-3"></div>
    </div>
{% endblock %}

courses/templates/courses/delete.html
{% extends 'base.html' %}

{% block title %}
Delete Course "{{ course.name }}"
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col">
            <form method="post">
                {% csrf_token %}
                <div class="text-center">
                    <p>Do you really want to remove student <strong>"{{ course.name }}"</strong></p>
                    <input class="btn btn-outline-primary" type="submit" value="Agree">
                    <a class="btn btn-outline-primary" href="{% url 'courses:list' %}">Back to list</a>
                </div>
            </form>
        </div>
        <div class="col-3"></div>
    </div>
{% endblock %}

courses/templates/courses/detail.html
{% extends 'base.html' %}

{% block title %}{{ title }}{% endblock %}

{% block content %}
<div class="row">
    <div class="col"></div>
    <div class="col align-self-center">
        <div class="card" style="width: 18rem;">
            <div class="card-body">
                <h5 class="card-title">{{ course.name }} {{ course.name }}</h5>
                <h6 class="card-subtitle mb-2 text-muted">{{ course.course_text }}</h6>
                <p class="card-text">{{ course.course_start |date:"y M Y" }}</p>
                <div class="text-center">
                    <a class="btn btn-outline-primary" href="{% url 'courses:update' courses.pk %}">Edit</a>
                    <a class="btn btn-outline-primary" href="{% url 'courses:list' %}">Back to list</a>
                </div>
            </div>
        </div>
    </div>
    <div class="col"></div>
</div>
{% endblock %}

courses/templates/courses/list.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}List of Course{% endblock %}

{% block content %}
    <div class="row">
        <div class="accordion" id="accordionExample">
            <div class="accordion-item">
                <h2 class="accordion-header" id="headingOne">
                    <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse"
                            data-bs-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
                        Search
                    </button>
                </h2>
                <div id="collapseOne" class="accordion-collapse collapse" aria-labelledby="headingOne"
                     data-bs-parent="#accordionExample">
                    <div class="accordion-body">
                        <div class="col-3"></div>
                        <div class="col">
                            <form method="get">
                                {{ filter_form.form|crispy }}
                                <input class="btn btn-outline-primary mt-3" type="submit" value="Search">
                            </form>
                        </div>
                        <div class="col-3"></div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
    <table class="table table-striped table-hover">
        <thead>
            <tr class="text-center">
                <th>Course name</th>
                <th>Course start </th>
                <th>Course text</th>
                <th>Course group</th>
                {% if user.is_authenticated %}
                    <th><i class="bi bi-pencil-fill"></i></th>
                    <th><i class="bi bi-trash3-fill"></i></th>
                {% endif %}
            </tr>
        <thead>
        <tbody>
            {% for st in courses %}
                <tr>
                    <td>{{ forloop.counter}}</td>
                    {% if user.is_authenticated %}
                        <td><a href="{% url 'courses:detail' st.pk %}">{{st.name}}</a></td>
                    {% else %}
                        <td>{{ st.name }}</td>
                    {% endif %}
                    <td class="text-center">{{st.course_start|date:"d M Y" }}</td>
                    <td class="text-center">{{st.course_text}}</td>
                    {% if user.is_authenticated %}
                        <td class="text-center"><a class="btn btn-outline-primary btn-sm" href="{% url 'courses:update' st.pk %}">Edit</a></td>
                        <td class="text-center"><a class="btn btn-outline-danger btn-sm" href="{% url 'courses:delete' st.pk %}">Remove</a></td>
                    {% endif %}
                </tr>
            {% endfor %}
        </tbody>
    </table>
    </div>
{% endblock %}

courses/templates/courses/update.html
{% extends 'base.html' %}

{% load crispy_forms_filters %}

{% block title %}
Update course "{{ form.name.value }}"
{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-3"></div>
        <div class="col">
            <form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <div class="text-center">
                    <input class="btn btn-outline-primary" type="submit" value="Udate">
                    <a class="btn btn-outline-primary" href="{% url 'courses:list' %}">Back to list</a>
                </div>
            </form>
        </div>
        <div class="col-3"></div>
    </div>
    <div class="row">
        {% with object_list=course.groups.all is_course=True %}
            {% include 'includes/groups_table.html' %}
        {% endwith %}
    </div>
{% endblock %}